// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gestimator
void gestimator(std::string file, std::string file_out = "", int maxHits = 3, bool verbose = false, bool remove_all_gaps = false);
RcppExport SEXP orthologr_gestimator(SEXP fileSEXP, SEXP file_outSEXP, SEXP maxHitsSEXP, SEXP verboseSEXP, SEXP remove_all_gapsSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type file(fileSEXP );
        Rcpp::traits::input_parameter< std::string >::type file_out(file_outSEXP );
        Rcpp::traits::input_parameter< int >::type maxHits(maxHitsSEXP );
        Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP );
        Rcpp::traits::input_parameter< bool >::type remove_all_gaps(remove_all_gapsSEXP );
        gestimator(file, file_out, maxHits, verbose, remove_all_gaps);
    }
    return R_NilValue;
END_RCPP
}
