OF2Orthologs <- function(orthologs_file) {
        
        if (!fs::file_exists(orthologs_file))
                stop("Please provide a valid path to the orthologs file generated by Orthofinder2.", call. = FALSE)
        
        suppressMessages(orthologs <- readr::read_tsv(orthologs_file, col_names = TRUE))
        
        return(orthologs)
}