# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
gestimator <- function(file, file_out = "", maxHits = 3L, verbose = FALSE, remove_all_gaps = FALSE) {
    invisible(.Call('orthologr_gestimator', PACKAGE = 'orthologr', file, file_out, maxHits, verbose, remove_all_gaps))
}

timesTwo <- function(x) {
    .Call('orthologr_timesTwo', PACKAGE = 'orthologr', x)
}

