# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Different <- function(seq1, seq2, skip_missing = FALSE, nucleic_acid = FALSE) {
    .Call(`_orthologr_Different`, seq1, seq2, skip_missing, nucleic_acid)
}

NumDiffs <- function(seq1, seq2, skip_missing = FALSE, nucleic_acid = FALSE) {
    .Call(`_orthologr_NumDiffs`, seq1, seq2, skip_missing, nucleic_acid)
}

toChar <- function(x) {
    .Call(`_orthologr_toChar`, x)
}

TsTv <- function(i, j) {
    .Call(`_orthologr_TsTv`, i, j)
}

NotAGap <- function(c) {
    .Call(`_orthologr_NotAGap`, c)
}

ambigousNucleotides <- function(codon) {
    .Call(`_orthologr_ambigousNucleotides`, codon)
}

codonPrecondition <- function(codon) {
    .Call(`_orthologr_codonPrecondition`, codon)
}

intToNuc <- function(i) {
    .Call(`_orthologr_intToNuc`, i)
}

nucToInt <- function(c) {
    .Call(`_orthologr_nucToInt`, c)
}

Universal <- function(codon) {
    .Call(`_orthologr_Universal`, codon)
}

TranslateCodon <- function(codon) {
    .Call(`_orthologr_TranslateCodon`, codon)
}

gestimator <- function(file, file_out = "", maxHits = 3L, verbose = FALSE, remove_all_gaps = FALSE) {
    invisible(.Call(`_orthologr_gestimator`, file, file_out, maxHits, verbose, remove_all_gaps))
}

